language: rust
dist: trusty
sudo: required
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libsystemd-journal-dev libsystemd-id128-dev libsystemd-login-dev libsystemd-daemon-dev

env:
  global:
    - RUST_BACKTRACE=1
    - LIBSYSTEMD_LDFLAGS="-l systemd-journal -l systemd-id128 -l systemd-login -l systemd-daemon"
  matrix:
    -
    - RELEASE=true
