language: rust
dist: trusty
sudo: required
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo add-apt-repository ppa:pitti/systemd -y
  - sudo apt-get update -qq
  - sudo apt-get install systemd -y

env:
  global:
    - RUST_BACKTRACE=1
  matrix:
    -
    - RELEASE=true
