[package]
name = "slog-journald"
version = "1.0.0"
authors = ["Thayne McCombs <astrothayne@gmail.com>"]
description = "Journald drain for slog-rs"
keywords = ["slog", "logging", "log", "journald", "systemd"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/slog-rs/"
homepage = "https://github.com/slog-rs/journald"
repository = "https://github.com/slog-rs/journald"
readme = "README.md"

[dependencies]
# git is temporary, should be removed once 1.1.0 is released
slog = {version = "1.1.0", git = "https://github.com/dpc/slog-rs" }
libc = "0.2"
libsystemd-sys = "0.0"
